---
global: # generall configs effecting one or multiple parts
  assignments:
    split_number: 1 # number of files fastq should be split for parallelization
assignments:
  exampleAssignment: # name of an example assignment (can be any string)
    bc_length: 15
    alignment_tool:
      tool: exact # bwa or exact
      configs:
        sequence_length: 170 # sequence length of design excluding adapters.
        alignment_start: 1 # start of the alignment in the reference/design_file
        # min_mapping_quality: 1  # integer >=0 Please use 1 when you have oligos that differ by 1 base in your reference/design_file
        # sequence_length:  # sequence length of design excluding adapters.
        #   min: 195
        #   max: 205
        # alignment_start:  # start of an alignment in the reference/design_file. Here using 15 bp adapters. Can be different when using adapter free approaches
        #   min: 15  # integer
        #   max: 17  # integer
    FW:
      - resources/assoc_basic/data/SRR10800986_1.fastq.gz
    BC:
      - resources/assoc_basic/data/SRR10800986_2.fastq.gz
    REV:
      - resources/assoc_basic/data/SRR10800986_3.fastq.gz
    design_file: resources/assoc_basic/design.fa
    configs:
      default: {} # name of an example filtering config
experiments:
  exampleCount:
    bc_length: 15
    umi_length: 10
    data_folder: resources/count_basic/data
    experiment_file: resources/count_basic/experiment.csv
    demultiplex: false
    assignments:
      fromFile:
        type: file
        assignment_file: resources/count_basic/SRR10800986_barcodes_to_coords.tsv.gz
      fromWorkflow:
        type: config
        assignment_name: exampleAssignment
        assignment_config: default
    # label_file: resources/labels.tsv # optional
    configs:
      default: 
        filter:
          bc_threshold: 1
          DNA: {}
          RNA: {}
