---
global: # generall configs effecting one or multiple parts
  threads: 1
  assignments:
    split_number: 1 # number of files fastq should be split for parallelization
assignments:
  exampleAssignment: # name of an example assignment (can be any string)
    bc_length: 15
    alignment_tool:
      tool: exact # bwa or exact
      configs:
        sequence_length: 170 # sequence length of design excluding adapters.
        alignment_start: 1 # start of the alignment in the reference
        # min_mapping_quality: 1  # integer >=0 Please use 1 when you have oligos that differ by 1 base in your reference/design file
        # sequence_length:  # sequence length of design excluding adapters.
        #   min: 195
        #   max: 205
        # alignment_start:  # start of an alignment in the reference. Here using 15 bp adapters. Can be different when using adapter free approaches
        #   min: 15  # integer
        #   max: 17  # integer
    FW:
      - resources/Assignment_BasiC/R1.fastq.gz
    BC:
      - resources/Assignment_BasiC/R2.fastq.gz
    REV:
      - resources/Assignment_BasiC/R3.fastq.gz
    reference: resources/design.fa
    configs:
      default: {} # name of an example filtering config
experiments:
  exampleCount:
    bc_length: 15
    umi_length: 10
    data_folder: resources/Count_Basic/data
    experiment_file: resources/example_experiment.csv
    demultiplex: false
    assignments:
      fromFile:
        type: file
        assignment_file: resources/SRR10800986_filtered_coords_to_barcodes.tsv.gz
      fromWorkflow:
        type: config
        assignment_name: exampleAssignment
        assignment_config: default
    design_file: resources/design.fa
    label_file: resources/labels.tsv # optional
    configs:
      default: {} # name of an example filtering config
