---
global:  # generall configs effecting one or multiple parts
  threads: 30
  assignments:
    split_number: 1  # number of files fastq should be split for parallelization
assignments:
  assignIGVFDesign:  # name of an example assignment (can be any string)
    bc_length: 15
    sequence_length:  # sequence length of design excluding adapters.
      min: 265
      max: 275
    alignment_start:  # start of an alignment in the reference. Here using 15 bp adapters. Can be different when using adapter free approaches
      min: 15  # integer
      max: 17  # integer
    min_mapping_quality: 1  # integer >=0 Please use 1 when you have oligos that differ by 1 base in your reference/design file
    FW:
      - /fast/groups/ag_kircher/MPRA/IGVF_Y1_design/resources/association_data/association1/IGVF_neuro_S1_R1_001.fastq.gz
    BC:
      - /fast/groups/ag_kircher/MPRA/IGVF_Y1_design/resources/association_data/association1/IGVF_neuro_S1_R2_001.fastq.gz
    REV:
      - /fast/groups/ag_kircher/MPRA/IGVF_Y1_design/resources/association_data/association1/IGVF_neuro_S1_R3_001.fastq.gz
    reference: /fast/groups/ag_kircher/MPRA/IGVF_Y1_design/resources/association_data/design.fa
    configs:
      exampleAssignmentConfig:  # name of an example filtering config
        min_support: 3
        fraction: 0.7