---
global:
  threads: 10
  assignments:
    split_number: 30
assignments:
  assocBasic:
    bc_length: 15
    sequence_length:
      min: 166
      max: 175
    alignment_start:
      min: 1
      max: 3
    FW:
      - data/SRR10800986_1.fastq.gz
    BC:
      - data/SRR10800986_2.fastq.gz
    REV:
      - data/SRR10800986_3.fastq.gz
    reference: data/design.fa
    configs:
      exampleConfig:
        min_support: 3
        fraction: 0.7
        unknown_other: false
        ambiguous: false
experiments:
  countBasic:
    bc_length: 15
    umi_length: 10
    data_folder: data
    experiment_file: data/experiment.csv
    demultiplex: false
    assignments:
      fromWorkflow:
        type: config
        assignment_name: assocBasic
        assignment_config: exampleConfig
    design_file: data/design.fa
    configs:
      exampleConfig:
        filter:
          bc_threshold: 10
          DNA:
            min_counts: 1
          RNA:
            min_counts: 1
