---
global:
  threads: 10
  assignments:
    split_number: 30
assignments:
  assocBasic:
    bc_length: 15
    sequence_length:
      min: 166
      max: 175
    alignment_start:
      min: 1
      max: 3
    FW:
      - data/SRR10800986_1.fastq.gz
    BC:
      - data/SRR10800986_2.fastq.gz
    REV:
      - data/SRR10800986_3.fastq.gz
    reference: data/design.fa
    configs:
      exampleConfig:
        min_support: 3
        fraction: 0.7
        unknown_other: true
        ambiguous: true
      exampleConfigTrueMatches:
        min_support: 3
        fraction: 0.7
        unknown_other: false
        ambiguous: false
